// ============================================
// CAMPAIGN CRUD QUERIES
// Client-side helpers for reading/writing structured campaigns
// ============================================

import { supabase } from "@/integrations/supabase/client";
import type { CanonicalChannel } from "@/lib/channels";
import type { StepType } from "@/lib/campaignTypes";

// ── Types (mirrors DB schema) ──────────────────────────────────────

export type CampaignMotion =
  | "outbound_prospecting"
  | "nurture"
  | "inbound_response"
  | "post_meeting"
  | "closing"
  | "re_engagement";

export type CampaignType = "general" | "industry";
export type CampaignStatus = "draft" | "active" | "paused" | "completed";

export interface Campaign {
  id: string;
  workspace_id: string;
  name: string;
  motion: CampaignMotion;
  default_channel: CanonicalChannel;
  include_meeting_cta: boolean;
  global_instructions: string | null;
  is_default: boolean;
  // Added in Unit A (migration 20260602000000_campaign_foundation.sql).
  // Typed here because the generated types.ts is regenerated by Lovable
  // only after the migration is applied; reads/writes below cast as needed.
  campaign_type: CampaignType;
  status: CampaignStatus;
  knowledge_ref: string | null;
  // Added in Unit B Phase 2 (migration 20260603120000): the kb_chunks.document_id
  // of the campaign's uploaded knowledge file. Authoring-time KB retrieval is
  // scoped to this document. Null until a file is ingested.
  knowledge_document_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface CampaignStep {
  id: string;
  campaign_id: string;
  step_number: number;
  step_type: StepType;
  channel: CanonicalChannel;
  framework: string | null;
  objective: string | null;
  cta_type: string;
  max_word_count: number | null;
  hard_rules: string[];
  generation_hints: string[];
  custom_instructions: string | null;
  delay_days: number;
  active: boolean;
  variant_group: string | null;
  created_at: string;
  updated_at: string;
}

export interface CampaignWithSteps extends Campaign {
  steps: CampaignStep[];
}

// ── Queries ─────────────────────────────────────────────────────────

/** Fetch campaign + steps for a lead (via leads.campaign_id) */
export async function fetchCampaignForLead(leadId: string): Promise<CampaignWithSteps | null> {
  // First get the lead's campaign_id
  const { data: lead } = await supabase
    .from("leads")
    .select("campaign_id")
    .eq("id", leadId)
    .maybeSingle();

  if (!lead?.campaign_id) return null;
  return fetchCampaignById(lead.campaign_id);
}

/** Fetch a campaign by ID with its steps */
export async function fetchCampaignById(campaignId: string): Promise<CampaignWithSteps | null> {
  const { data: campaign } = await supabase
    .from("campaigns")
    .select("*")
    .eq("id", campaignId)
    .maybeSingle();

  if (!campaign) return null;

  const { data: steps } = await supabase
    .from("campaign_steps")
    .select("*")
    .eq("campaign_id", campaignId)
    .order("step_number", { ascending: true });

  return {
    ...campaign,
    steps: (steps || []) as unknown as CampaignStep[],
  } as unknown as CampaignWithSteps;
}

/** List all campaigns for a workspace */
export async function fetchWorkspaceCampaigns(workspaceId: string): Promise<Campaign[]> {
  const { data } = await supabase
    .from("campaigns")
    .select("*")
    .eq("workspace_id", workspaceId)
    .order("created_at", { ascending: false });

  return (data || []) as unknown as Campaign[];
}

/** Get the default campaign for a workspace + motion */
export async function fetchDefaultCampaign(
  workspaceId: string,
  motion: CampaignMotion = "outbound_prospecting",
): Promise<CampaignWithSteps | null> {
  const { data: campaign } = await supabase
    .from("campaigns")
    .select("*")
    .eq("workspace_id", workspaceId)
    .eq("motion", motion)
    .eq("is_default", true)
    .maybeSingle();

  if (!campaign) return null;

  const { data: steps } = await supabase
    .from("campaign_steps")
    .select("*")
    .eq("campaign_id", campaign.id)
    .order("step_number", { ascending: true });

  return {
    ...campaign,
    steps: (steps || []) as unknown as CampaignStep[],
  } as unknown as CampaignWithSteps;
}

/** Assign a campaign to a lead (or clear it with null) */
export async function assignCampaignToLead(leadId: string, campaignId: string | null) {
  return supabase
    .from("leads")
    .update({ campaign_id: campaignId } as any)
    .eq("id", leadId);
}

// ── Mutations (Unit A) ──────────────────────────────────────────────

/** A step as authored in the setup flow, before it has a DB id. */
export interface DraftCampaignStep {
  step_number: number;
  step_type: StepType;
  channel: CanonicalChannel;
  delay_days: number;
  cta_type: string;
  custom_instructions: string;
  active: boolean;
  variant_group?: string | null;
}

export interface CreateCampaignInput {
  workspace_id: string;
  name: string;
  campaign_type: CampaignType;
  default_channel: CanonicalChannel;
  include_meeting_cta: boolean;
  global_instructions: string;
  knowledge_ref?: string | null;
  steps: DraftCampaignStep[];
}

function draftStepToRow(campaignId: string, s: DraftCampaignStep) {
  return {
    campaign_id: campaignId,
    step_number: s.step_number,
    step_type: s.step_type,
    channel: s.channel,
    cta_type: s.cta_type,
    delay_days: s.delay_days,
    custom_instructions: s.custom_instructions || null,
    active: s.active,
    variant_group: s.variant_group ?? null,
  };
}

/**
 * Create a draft campaign and its steps. Saved with status='draft' —
 * enrollment and sending are later units. Returns the new campaign id.
 */
export async function createCampaignWithSteps(input: CreateCampaignInput): Promise<string> {
  const { data: campaign, error } = await supabase
    .from("campaigns")
    .insert({
      workspace_id: input.workspace_id,
      name: input.name,
      motion: "outbound_prospecting",
      campaign_type: input.campaign_type,
      status: "draft",
      default_channel: input.default_channel,
      include_meeting_cta: input.include_meeting_cta,
      global_instructions: input.global_instructions || null,
      knowledge_ref: input.knowledge_ref ?? null,
    } as any)
    .select("id")
    .single();

  if (error || !campaign) {
    throw new Error(error?.message || "Failed to create outreach");
  }

  const campaignId = (campaign as { id: string }).id;

  if (input.steps.length > 0) {
    const { error: stepsError } = await supabase
      .from("campaign_steps")
      .insert(input.steps.map((s) => draftStepToRow(campaignId, s)) as any);
    if (stepsError) {
      // Roll back the orphaned campaign so a failed save doesn't leave a stub.
      await supabase.from("campaigns").delete().eq("id", campaignId);
      throw new Error(stepsError.message || "Failed to save outreach steps");
    }
  }

  return campaignId;
}

/** Update editable campaign-level fields. */
export async function updateCampaign(
  campaignId: string,
  patch: Partial<Pick<Campaign, "name" | "global_instructions" | "include_meeting_cta" | "knowledge_ref" | "knowledge_document_id" | "status">>,
) {
  const { error } = await supabase
    .from("campaigns")
    .update(patch as any)
    .eq("id", campaignId);
  if (error) throw new Error(error.message || "Failed to update outreach");
}

/**
 * Replace the full step set for a campaign (used when the rep nudges
 * days-between or removes a touch in the review / detail screens).
 * Steps are renumbered 1..N so the sequence has no gaps.
 */
export async function replaceCampaignSteps(campaignId: string, steps: DraftCampaignStep[]) {
  const { error: delError } = await supabase
    .from("campaign_steps")
    .delete()
    .eq("campaign_id", campaignId);
  if (delError) throw new Error(delError.message || "Failed to update steps");

  const renumbered = steps.map((s, i) => ({ ...s, step_number: i + 1 }));
  if (renumbered.length > 0) {
    const { error: insError } = await supabase
      .from("campaign_steps")
      .insert(renumbered.map((s) => draftStepToRow(campaignId, s)) as any);
    if (insError) throw new Error(insError.message || "Failed to update steps");
  }
}

/** Delete a campaign. Steps cascade; enrolled leads' campaign_id is set null by FK. */
export async function deleteCampaign(campaignId: string) {
  const { error } = await supabase.from("campaigns").delete().eq("id", campaignId);
  if (error) throw new Error(error.message || "Failed to delete outreach");
}

// ── Campaign membership (the "People" list) ─────────────────────────

export interface CampaignLead {
  id: string;
  name: string;
  company: string | null;
  email: string | null;
  industry: string | null;
}

/** Leads currently enrolled in (assigned to) a campaign. */
export async function fetchCampaignLeads(campaignId: string): Promise<CampaignLead[]> {
  const { data } = await supabase
    .from("leads")
    .select("id, name, company, email, industry")
    .eq("campaign_id", campaignId)
    .order("name", { ascending: true });
  return (data || []) as unknown as CampaignLead[];
}

/**
 * Add many leads to a campaign at once (late joiners are fine — they just
 * associate). Returns the number of leads actually added. The UPDATE is
 * constrained two ways, both fail-closed, because the picker uses the
 * non-workspace-scoped, no-campaign-filter getLeadsList():
 *  1. `workspace_id` = the campaign's own workspace — a multi-workspace rep
 *     can't pull a cross-workspace lead in.
 *  2. `campaign_id IS NULL` — never move a lead OUT of an outreach it's already
 *     in. Stealing a lead from an active campaign would silently halt that
 *     campaign's sends (and, since drafts are loader-gated, drop the lead to
 *     legacy instructions). Already-assigned leads are skipped; callers surface
 *     the skipped count rather than reporting a silent success.
 */
export async function addLeadsToCampaign(leadIds: string[], campaignId: string): Promise<number> {
  if (leadIds.length === 0) return 0;

  const { data: campaign, error: cErr } = await supabase
    .from("campaigns")
    .select("workspace_id")
    .eq("id", campaignId)
    .single();
  if (cErr || !campaign) throw new Error(cErr?.message || "Outreach not found");

  const { data, error } = await supabase
    .from("leads")
    .update({ campaign_id: campaignId } as any)
    .in("id", leadIds)
    .eq("workspace_id", (campaign as { workspace_id: string }).workspace_id)
    .is("campaign_id", null)
    .select("id");
  if (error) throw new Error(error.message || "Failed to add people");
  return (data || []).length;
}

// ── Suppression list (workspace do-not-contact) ─────────────────────
// Stored in campaign_suppression_list. Separate from leads.unsubscribed.
// Enforcement (read-before-enroll / read-before-send, fail-closed) lands in
// Unit C alongside the send path — it must COMPOSE with the existing
// leads.unsubscribed / stop_on_unsubscribe opt-out, not replace it. Unit A/B
// have no send path, so this list is inert until then (the UI says as much).

export type SuppressionKind = "email" | "domain";

export interface SuppressionEntry {
  id: string;
  workspace_id: string;
  kind: SuppressionKind;
  value: string;
  created_at: string;
}

export async function fetchSuppressionList(workspaceId: string): Promise<SuppressionEntry[]> {
  const { data } = await supabase
    .from("campaign_suppression_list" as any)
    .select("*")
    .eq("workspace_id", workspaceId)
    .order("created_at", { ascending: false });
  return (data || []) as unknown as SuppressionEntry[];
}

/** Classify a raw entry as a domain ("acme.com") or an email ("a@acme.com"). */
export function classifySuppressionValue(raw: string): { kind: SuppressionKind; value: string } | null {
  const value = raw.trim().toLowerCase();
  if (!value) return null;
  if (value.includes("@")) {
    // Looks like an email — require a dot in the domain part.
    const [, domain] = value.split("@");
    if (!domain || !domain.includes(".")) return null;
    return { kind: "email", value };
  }
  // Bare domain — must contain a dot and no spaces.
  if (!value.includes(".") || /\s/.test(value)) return null;
  return { kind: "domain", value };
}

/** Add entries (deduped by the table's UNIQUE constraint). Returns count added. */
export async function addSuppressionEntries(workspaceId: string, rawValues: string[]): Promise<number> {
  const rows = rawValues
    .map(classifySuppressionValue)
    .filter((r): r is { kind: SuppressionKind; value: string } => r !== null)
    .map((r) => ({ workspace_id: workspaceId, kind: r.kind, value: r.value }));
  if (rows.length === 0) return 0;
  const { data, error } = await supabase
    .from("campaign_suppression_list" as any)
    .upsert(rows as any, { onConflict: "workspace_id,kind,value", ignoreDuplicates: true })
    .select("id");
  if (error) throw new Error(error.message || "Failed to update do-not-contact list");
  return (data || []).length;
}

export async function removeSuppressionEntry(id: string) {
  const { error } = await supabase
    .from("campaign_suppression_list" as any)
    .delete()
    .eq("id", id);
  if (error) throw new Error(error.message || "Failed to remove entry");
}

// ── Generated per-touch content (Unit B Phase 2) ────────────────────
// Stored in campaign_step_content, one row per (campaign × step × variant_group;
// NULL variant_group = General / fallback). The flat channel fields mirror the
// currently-selected option; options_json holds the "couple of options" the rep
// can pick between. is_edited locks a touch — only an explicit per-touch Rewrite
// regenerates it. Cast `as any` because the table isn't in the generated
// types.ts until Lovable applies the migration (mirrors the suppression list).

export interface StepContentOption {
  subject?: string;
  body?: string;
  talking_points?: string;
  voicemail_script?: string;
  sms_text?: string;
}

export interface StepContent {
  id: string;
  campaign_id: string;
  step_number: number;
  variant_group: string | null;
  subject: string | null;
  body: string | null;
  talking_points: string | null;
  voicemail_script: string | null;
  sms_text: string | null;
  options_json: StepContentOption[] | null;
  selected_option: number | null;
  is_edited: boolean;
  updated_at?: string;
}

const STEP_CONTENT_KEY = (variantGroup: string | null) =>
  variantGroup == null || variantGroup.trim() === "" ? null : variantGroup;

/** All generated content rows for a campaign (every variant). */
export async function fetchStepContent(campaignId: string): Promise<StepContent[]> {
  const { data } = await supabase
    .from("campaign_step_content" as any)
    .select("*")
    .eq("campaign_id", campaignId)
    .order("step_number", { ascending: true });
  return (data || []) as unknown as StepContent[];
}

/** Fields a write may set on a content row. */
export type StepContentWrite = Partial<
  Pick<
    StepContent,
    | "subject"
    | "body"
    | "talking_points"
    | "voicemail_script"
    | "sms_text"
    | "options_json"
    | "selected_option"
    | "is_edited"
  >
>;

/**
 * Insert-or-update a single (campaign × step × variant) content row. Manual
 * upsert (select-then-write) because the uniqueness is a COALESCE expression
 * index, which PostgREST's onConflict can't target.
 */
export async function upsertStepContent(
  campaignId: string,
  stepNumber: number,
  variantGroup: string | null,
  write: StepContentWrite,
): Promise<void> {
  const vg = STEP_CONTENT_KEY(variantGroup);
  let findQ = supabase
    .from("campaign_step_content" as any)
    .select("id")
    .eq("campaign_id", campaignId)
    .eq("step_number", stepNumber);
  findQ = vg == null ? findQ.is("variant_group", null) : findQ.eq("variant_group", vg);
  const { data: existing } = await findQ.maybeSingle();

  if ((existing as { id?: string } | null)?.id) {
    const { error } = await supabase
      .from("campaign_step_content" as any)
      .update(write as any)
      .eq("id", (existing as unknown as { id: string }).id);
    if (error) throw new Error(error.message || "Failed to save content");
  } else {
    const { error } = await supabase
      .from("campaign_step_content" as any)
      .insert({
        campaign_id: campaignId,
        step_number: stepNumber,
        variant_group: vg,
        ...write,
      } as any);
    if (error) throw new Error(error.message || "Failed to save content");
  }
}

/** Save a rep's inline edit — locks the touch (is_edited=true). */
export async function saveStepEdit(
  campaignId: string,
  stepNumber: number,
  variantGroup: string | null,
  fields: Pick<StepContent, "subject" | "body" | "talking_points" | "voicemail_script" | "sms_text">,
): Promise<void> {
  await upsertStepContent(campaignId, stepNumber, variantGroup, { ...fields, is_edited: true });
}

/**
 * Pick one of the generated options. Copies that option's fields into the flat
 * columns. NEVER wipes a rep edit: refuses if the row is already edited, and the
 * UPDATE itself is filtered on `is_edited = false` so a concurrent edit in
 * another tab/session (set between this read and write) can't be clobbered —
 * the update simply matches zero rows. Returns true only when the pick applied;
 * false means the row was edited (or absent) and the caller should refresh.
 */
export async function selectStepOption(
  campaignId: string,
  stepNumber: number,
  variantGroup: string | null,
  optionIndex: number,
  option: StepContentOption,
): Promise<boolean> {
  const vg = STEP_CONTENT_KEY(variantGroup);
  let findQ = supabase
    .from("campaign_step_content" as any)
    .select("id, is_edited")
    .eq("campaign_id", campaignId)
    .eq("step_number", stepNumber);
  findQ = vg == null ? findQ.is("variant_group", null) : findQ.eq("variant_group", vg);
  const { data: existing } = await findQ.maybeSingle();
  const row = existing as { id?: string; is_edited?: boolean } | null;

  // Picking an option only makes sense on an existing, un-edited row. Bail
  // (without writing) on a missing row or one the rep has already edited.
  if (!row?.id || row.is_edited === true) return false;

  const { data, error } = await supabase
    .from("campaign_step_content" as any)
    .update({
      selected_option: optionIndex,
      subject: option.subject ?? null,
      body: option.body ?? null,
      talking_points: option.talking_points ?? null,
      sms_text: option.sms_text ?? null,
      // voicemail_script is a companion field, not part of the option set — leave it.
    } as any)
    .eq("id", row.id)
    .eq("is_edited", false) // TOCTOU guard: a concurrent edit makes this match 0 rows
    .select("id");
  if (error) throw new Error(error.message || "Couldn't switch option");
  return (data || []).length > 0;
}

// ── Campaign collateral (Unit D) ────────────────────────────────────
// AI-drafted, rep-editable one-pagers / walkthroughs stored in
// campaign_collateral (one row per campaign × type × variant_group; NULL =
// General). is_edited locks a draft (regenerate confirms before replacing).
// attached_step_number is a LIGHTWEIGHT logical link ("offered with touch N"),
// NOT a send-time attachment. Cast `as any` until Lovable regenerates types.ts.

export type CollateralType = "one_pager" | "walkthrough";

export interface CampaignCollateral {
  id: string;
  campaign_id: string;
  collateral_type: CollateralType;
  variant_group: string | null;
  title: string | null;
  body: string | null;
  is_edited: boolean;
  attached_step_number: number | null;
  updated_at?: string;
}

export type CollateralWrite = Partial<
  Pick<CampaignCollateral, "title" | "body" | "is_edited" | "attached_step_number">
>;

/** All collateral rows for a campaign (every type + variant). */
export async function fetchCampaignCollateral(campaignId: string): Promise<CampaignCollateral[]> {
  const { data } = await supabase
    .from("campaign_collateral" as any)
    .select("*")
    .eq("campaign_id", campaignId)
    .order("collateral_type", { ascending: true });
  return (data || []) as unknown as CampaignCollateral[];
}

/**
 * Insert-or-update a single (campaign × type × variant) collateral row. Manual
 * upsert (select-then-write) because the uniqueness is a COALESCE expression
 * index, which PostgREST's onConflict can't target.
 */
export async function upsertCollateral(
  campaignId: string,
  type: CollateralType,
  variantGroup: string | null,
  write: CollateralWrite,
): Promise<void> {
  const vg = STEP_CONTENT_KEY(variantGroup);
  let findQ = supabase
    .from("campaign_collateral" as any)
    .select("id")
    .eq("campaign_id", campaignId)
    .eq("collateral_type", type);
  findQ = vg == null ? findQ.is("variant_group", null) : findQ.eq("variant_group", vg);
  const { data: existing } = await findQ.maybeSingle();

  if ((existing as unknown as { id?: string } | null)?.id) {
    const { error } = await supabase
      .from("campaign_collateral" as any)
      .update(write as any)
      .eq("id", (existing as unknown as { id: string }).id);
    if (error) throw new Error(error.message || "Failed to save collateral");
  } else {
    const { error } = await supabase
      .from("campaign_collateral" as any)
      .insert({ campaign_id: campaignId, collateral_type: type, variant_group: vg, ...write } as any);
    if (error) throw new Error(error.message || "Failed to save collateral");
  }
}

/** Save a rep's inline edit — locks the draft (is_edited=true). */
export async function saveCollateralEdit(
  campaignId: string,
  type: CollateralType,
  variantGroup: string | null,
  fields: Pick<CampaignCollateral, "title" | "body">,
): Promise<void> {
  await upsertCollateral(campaignId, type, variantGroup, { ...fields, is_edited: true });
}

export async function deleteCollateral(id: string): Promise<void> {
  const { error } = await supabase.from("campaign_collateral" as any).delete().eq("id", id);
  if (error) throw new Error(error.message || "Failed to delete collateral");
}

/** Link a collateral row to a touch (or clear with null). Logical link only. */
export async function attachCollateralToStep(id: string, stepNumber: number | null): Promise<void> {
  const { error } = await supabase
    .from("campaign_collateral" as any)
    .update({ attached_step_number: stepNumber } as any)
    .eq("id", id);
  if (error) throw new Error(error.message || "Failed to link collateral");
}
